# Generated by Django 3.1.5 on 2021-01-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0005_auto_20210108_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='farmer_username',
        ),
    ]
