# Generated by Django 4.0.5 on 2022-08-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='usertype',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
