# Generated by Django 4.0.5 on 2022-09-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0009_comp'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jbtitle', models.CharField(max_length=200, null=True)),
                ('jbname', models.CharField(max_length=200, null=True)),
                ('jbdes', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
