# Generated by Django 4.0.5 on 2022-09-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0013_rename_mob_info_mob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='farmer_name',
        ),
    ]
